### ISSUE TITLE
Move label inheritance to start of declare_design()

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#100]
when a function like 

alex_estimator <- declare_estimator()

is run without

label = "my_estimator"

we need a label.

The right label is "alex_estimator", which can be obtained when we do

declare_design(estimator = alex_estimator)

**Comment by jaspercooper** [comment]
Currently we are getting this in get_estimates, right? I could see enormous speed improvements to getting labels at the design declaration phase, rather than having diagnose_design() get the estimator labels every single time it runs get_estimates(). 

But I would suggest that we retain get_estimates()'s ability to get estimator labels in the cases where it is being used outside of diagnose_design(), right?

**Comment by graemeblair** [comment]
Agreed -- I'm going to implement this now in declare_design because there are some bugs associated with this issue. I will not alter get_estimates / get_estimands, which will not try to make labels because labels will not be NULL post-declare_design.

**Comment by graemeblair** [comment]
fixed in new-diagnose-design branch
