### ISSUE TITLE
append expand_design parameters to diagnosis dataframe

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#135]
thanks!

**Comment by nfultz** [comment]
supporting functions as options to fill_in would preclude this.

**Comment by graemeblair** [comment]
can we get the name of the function via `substitute` and include that in the diagnosis df?

**Comment by nfultz** [comment]
If you set the names on the list of designs, it should get threaded through.

**Comment by jaspercooper** [comment]
Where are we at with this? To my mind the purpose of `expand_design()` is for power curves and MDEs, etc. Without knowing which parameters the diagnosands correspond to this is impossible. And sure, people can expand.grid() the arguments and merge them into the diagnosands_df, but there is so much scope for that to go wrong (i.e., changing the order of the arguments in expand.grid).

Propose to do a PR with the following implementation: 
- `template_args_matrix` gets a `design_ID` added 
- the `template_args_matrix` inside `expand_design()` gets stored as a `parameters` attribute inside the object returned by `expand_design()` 
- if `diagnose_design()` finds `parameters` in the attributes of the `designs` it merges them into `simulations_df` and `diagnosands_df`

I have thoughts on how to bring in functions, vectors and other stuff like that using an approach I wrote in DD's past life, but I think that requires a separate issue.

**Comment by nfultz** [comment]
Sets of designs aren't really a thing right now. 

You should probably append the individual rows of the matrix to each design seperately - eg in expand_design change the `what=template` to something like `what=function(...) structure(template(...), args=list(...))`. 

Then in diagnose_single_design, check if the args attribute is present and maybe add it to the return list. then Update diagnose_design to cbind them on to the diagnosands data frame.

**Comment by macartan** [comment]
Think something like this is important, I have needed it  a few times
already. And it would be great to be able to just plot N against power etc
straight from diagnosands_df

JC -- not following your first step but yes if (2) expand_design etc can
add an attribute with the various parameter fixed parameters = list(N = 4,
ate = 2) to each design then (3) simulate_design could add one column for
each attribute N, ate, etc

note:

1. If you do this I would like to have the changes to diagnose_design
approved first since the structure change matters
2. Under the new structure this would be done as part of simulate_design
and enter into simulations_df; diagnosands_df would then inherit it
3. Suggest this be an option set to FALSE for two reasons (1) otherwise
this will change the shape of existing exported diagnoses and break current
code (2) this could be verbose and often not needed (3) if not used
deliberately this could be messy in particular because:
4. Need to consider behavior where multiple designs have different
parameters marked. eg design one has  parameters = list(N = 4) and another
has  parameters = list(ate = 2) and someone diagnoses these jointly. In
that case all parameters will not be available for all designs and you may
end up with many columns with a bunch of blanks.

**Comment by macartan** [comment]
There is now something along those lines in the m_diagnosis branch; adding arguments used in expand as an attribute to a design and then picking these up in simulate design and diagnose_design

Output looks like this:

```
> designs   <- redesign(simple_two_arm_design, N = c(60, 70, 80), name_stub = "two_arm_")
> diagnose_design(designs, add_parameters = TRUE)

Research design diagnosis, based on 500 simulations and 100 bootstrap draws.

 Design ID Estimator Label Coefficient Estimand Label  N   Bias   RMSE  Power Coverage Mean Estimate SD Estimate
 two_arm_1    my_estimator           Z            ATE 60  -0.01   0.24   0.96     0.96          0.98        0.27
                                                         (0.01) (0.01) (0.01)   (0.01)        (0.01)      (0.01)
 two_arm_2    my_estimator           Z            ATE 70   0.00   0.22   0.98     0.95          1.00        0.26
                                                         (0.01) (0.01) (0.01)   (0.01)        (0.01)      (0.01)
 two_arm_3    my_estimator           Z            ATE 80  -0.01   0.22   0.99     0.95          1.00        0.25
                                                         (0.01) (0.01) (0.00)   (0.01)        (0.01)      (0.01)
 Mean Se Type S Rate Mean Estimand
    0.25        0.00          0.99
  (0.00)      (0.00)        (0.01)
    0.23        0.00          1.00
  (0.00)      (0.00)        (0.01)
    0.22        0.00          1.00
  (0.00)      (0.00)        (0.00)
```

**Comment by graemeblair** [comment]
addressed in https://github.com/DeclareDesign/DeclareDesign/pull/191
