### ISSUE TITLE
doubled estimator labels to not produce error, but some disappear

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#190]
```
two_arm <- simple_two_arm_design / declare_step(X = rnorm(100)) / 
                   declare_estimator(Y~Z+X, model = lm_robust, estimand = "ATE")  

> get_estimates(two_arm)
  estimator_label coefficient       est        se            p  ci_lower ci_upper estimand_label
1    my_estimator           Z 0.9077030 0.2078980 3.432871e-05 0.4945595 1.320846            ATE
2    my_estimator           Z 0.9061416 0.2097501 3.771943e-05 0.4898457 1.322438            ATE
```
<- This is OK

```
> diagnose_design(two_arm, sims = 2)$diagnosands[, 1:5]
                   estimator_label coefficient estimand_label        bias   se(bias)
ATE.my_estimator.Z    my_estimator           Z            ATE -0.05066497 0.03662236

```
<- This is not OK -- one estimator has disappeared.

Possible to add a check that there is no doubling of an estimator label?

**Comment by nfultz** [comment]
It hasn't disappeared - the two estimates were aggregated in the diagnosis step.

There's already a check for this in `declare_design`, which is by far the most common use case. 

Given that there are so many different ways to alter a design after the fact (at least  six),  this probably isn't solvable in a general way without a substantial amount of work.  We should probably add some more cautionary language to the man pages for those functions.

The best solution I can think of for this specific problem is for estimators to also add a synthetic column to the output (ex estimator_id = memory address of object or step index in list) so that diagnosands will never aggregate over two different estimator steps (although that would make it more difficult for certain examples around aggregating estimates such as backdoors  to estimating variance components in mixed models). Also, this would place some extra burden if someone ever wanted to write a custom estimator handler instead of using the default.

**Comment by macartan** [comment]
how about adding sthg like this to the top of diagnose_design:

```
check_designs <- function(designs) {
  for (j in 1:length(designs)) {
  if (any(duplicated(run_design(designs[[j]])[[1]]$estimator_label))) {
  stop(paste("design ", j, " has repeated estimator labels"))
  }
  }
}
```

then:

```
two_arm <- simple_two_arm_design / declare_estimator(Y~Z, model =
lm_robust, estimand = "ATE")

> check_designs(list(simple_two_arm_design, two_arm))
Error in check_designs(list(simple_two_arm_design, two_arm)) :
  design  2  has repeated estimator labels
```

maybe an lapply version would return a list of designs with this issue
rather than the first one only

**Comment by nfultz** [comment]
That seems fine, you should probably write it as `check_design()` for a single design, and lapply it.  Also replace the checks in declare design with a call to `check_design` so that there is a single place to define what makes a design valid.

**Comment by macartan** [comment]
This produces fails on models with coefficients; eg:

```
my_design <- declare_design(
  my_pop = declare_population(N=30, noise=rnorm(N, mean = 0, sd=1), X=1:N, Y = alpha + beta*X + noise)
  ,
  theta = declare_estimand(
    `(Intercept)`=alpha,
    X = beta,
    coefficients = TRUE
  )
  ,
  OLS = declare_estimator(Y~X, model=lm, estimand="theta", coefficients=TRUE)
)
run_design(my_design)[[1]]$estimator_label

[1] "OLS" "OLS"
```

Here both estimators are labelled OLS.

I suggest for simplicity to keep the warning as is and insist on having specific labels for each estimator, as in: 

    OLS = declare_estimator(Y~X, model=lm, estimand="theta", coefficients=TRUE, label = c("Constant", "b_X"))

This works currently. Objections?

**Comment by macartan** [comment]
Realize that doing this based on `run_design(des)[[1]]$estimator_label` is not good since at this point an estimator label may be double because of proper matching of a single estimator to multiple estimands

**Comment by graemeblair** [comment]
Suggest we add this to the validation function for designs - gives warning/error saying you have dupe labels

**Comment by nfultz** [comment]
It's already in the validation for declare_design, this ticket is for doing
so in diagnose_design.

**Comment by graemeblair** [comment]
Thanks, I see you already noted that.

**Comment by graemeblair** [comment]
I am closing this, because this is well handled by `declare_design` which has very good validation. the slash operator is handy, but I don't think we should  bend over backwards to support it when everything works well with `declare_design`. The kind of checking that does is not possible with the slash operator.
