### ISSUE TITLE
Better default names

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/DeclareDesign#227]
If the convention is going to be `U + Y + Z + Q + S + R + A` to build designs, we should build better default names for anonymous steps. eg

```
declare_population(N=100, foo=1) + declare_sampling(m=50)
```

should be named something like U and S instead of being named after the deparsed call. Perhaps it could be letter dot dot position.

For each step type, declare a default letter, and use that to make names that look like U..1, S..2, etc.

**Comment by macartan** [comment]
I like this.

Though in general think we should encourage people to name steps

U <- declare_population(N=100, foo=1)

S <- declare_sampling(m=50)

U + S

**Comment by acoppock** [comment]
Maybe the best default names would respect the `declare_*` conventions? I think single letters are too terse.

so
`population`
`sampling`
`assignment`
`potential_outcomes`
`reveal`
`estimand`
`estimator`

how about `_stepnumber` instead of `..stepnumber`, since dd is an underscore place.

**Comment by macartan** [comment]
I am not seeing terse as a problem, rather as an advantage as it helps you
see the structure of a design quickly.  Some designs have many steps, I was
on one today with 15 or 16 steps, and a convention makes them more legible.
People can of course deviate as necessary but think only worth doing when
it is really informative.

**Comment by jaspercooper** [comment]
I don't really care so much about the terse vs. verbose distinction when people use their own names, both are fine. 

For *defaults*, I can see the attraction of single letters because they are very modular and quick. But I ultimately prefer full words since single letters are ambiguous. 

Y: could be a reveal step but could also be a potential outcome step
R: makes me think of reveal or random sampling / assignment, or an attrition potential outcome
A: we have in the paper A_M and A_A -- not clear that Q should be inquiry, why not I (well, we can't have I, T or F, since these are privileged in R)
S: is it step or sampling

I vote for full names and in general would suggest we always err on the side of verbose code that reads as much like an english sentence as possible.

**Comment by jaspercooper** [comment]
Since I never responded to the last thread: 
> Declare each step explicitly; including Reveal. So discourage this kind of thing: 
> design_stub <- pop + ... + declare_reveal() and this replace_step(design, my_assignment, 
 dplyr::mutate(words="HIARYLAH"))

Agreed on this as a principle (not as a restriction on how you can use software).

> Use short names for steps, I think there are obvious short names and that if explanation is needed this might be better done with labels. (The main one I am not happy with here is Y which ideally would be F for functional equations and then R would be Y. But don;t want to overload F.)

Do not agree on this point for defaults for reasons above. I am more concerned about legibility than ease of coding in this project.  

> Group Reveal beside Assignment declarations when possible. It is part of Data.
> Group estimates at the end -- this is almost always possible
> Group estimands together when possible (sometimes not, e.g. if data structure changes, for example due to sampling)

Yes to these as principles / advice. Is that how they are intended?

> Link estimates to estimand via estimand name rather than step name

I quite like just giving the object to the estimator. Getting the object name right is usually easier because R will auto-suggest, but getting the estimand name right can go wrong (i.e. capitalization, spaces, etc.). Is there a strong reason to prefer estimand names?

**Comment by nfultz** [comment]
+1 for linking by object - the ambiguity from NSE in that part of the package is more trouble than its worth.

**Comment by macartan** [comment]
I don't feel strongly on this point but I have a set of cases where there
are multiple estimands defined in an object and the estimand name needs to
bit used here. If that's right that's grounds for just doing as a
convention.

But I am not sure what the ambiguity issues are that worry Neal

**Comment by acoppock** [comment]
Looks like we're converging on the not-that-terse, but not-that-long defaults suggested above? I'm also pro linking-by-object.

**Comment by graemeblair** [comment]
I vote for these short names:

```
population
sampling
assignment
potential_outcomes
reveal_outcomes
estimand
estimator
```

For reasons above and we are already asking users to learn a whole new language, another set of abbreviations is hard to remember, using `_1` to disambiguate multiple steps.

I'm going to work through some examples on the name-by-object-or-NSE thing.

**Comment by macartan** [comment]
OK I'll yield on this though the information to ink ratio pains me.

My last suggestion on this would be to shorten to the two long ones to
potentials and reveal. Remember these names do not provide the information
to include the steps, they just orient people. And GB there is no
suggestion that we have others adopt these. This is just to have a
consistent look in modules and designers.

We might want something for declare_step as well; these are generally data
manipulations so I"d be OK with something like transform; modify; of h/t to
dplyr mutate
