### ISSUE TITLE
compare_designs

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#263]
maybe get_code on each design; diff

**Comment by acoppock** [comment]
what's the best implementation of diff for R?  there's diffr https://cran.r-project.org/package=diffr

would prefer not to depend on a package if possible

**Comment by nfultz** [comment]
`tools::Rdiff` - not sure how it works on windows but docs claim it does.

**Comment by rdrr1990** [comment]
Just started working on this on my branch -- https://github.com/DeclareDesign/DeclareDesign/blob/mohanty/R/compare_designs.R

**Comment by macartan** [comment]
​​
Great stuff Pete; this is really important functionality

Here are some thoughts on approaches to comparing designs:

# A. Code comparison -- 
A1 some simple stats:compare length, number of lines that are different, 
A2 print out github style differences in code to make human comparison easy. 

A is the most basic and will be very useful, bot not necessarily the most informative -- it might not really alert one to important differences. Moreover some kinds of code differences in the deep design will not be caught. To wit: the following two different designs have the same print_code

```
g = function(X) 2*x
design_1 <- declare_population(N = 2, X = 1:2, Y = g(X)) + NULL

g = function(X) 3*x
design_2 <- declare_population(N = 2, X = 1:2, Y = g(X)) + NULL

> print_code(design_1)
population <- declare_population(N = 2, X = 1:2, Y = g(X)) 

my_design <- construct_design(steps = steps) 

> print_code(design_2)
population <- declare_population(N = 2, X = 1:2, Y = g(X)) 

my_design <- construct_design(steps = steps) ```
```
Not sure what the final line is going there, but the point is that the code looks different for these two designs because of the dark design issue.

# B Structural comparison

A comparison of the number of steps of each type:
eg dgp steps, estimators setps, estimand steps

You could imagine this output as a nice table. 

# C Arguments comparison

Say two designs have the same code but the arguments have different values. Can this be figured out?
```
> N = 10
> design_1 <- declare_population(N = N, X = 1:N) + NULL
> 
> N = 20
> design_2 <- declare_population(N = N, X = 1:N) + NULL
```
Could we imagine listing differences in values of arguments (at each step)?

# D Functional comparisons
Do the *steps* do similar things?
I imagine the most useful here would be an operation like:

```
df <- draw_data(design_1)
A1 <- get_estimates(design_1, df)
A2 <- get_estimates(design_2, df)
```
and then compare to see where the estimates are the same or not; this could get tricky of course if the labels of estimates change; but a good first step would be to have how many of A1 estimates are *in* A2 and how many of the A2 estimates are *in* A1

One could imagine other functional comparisons such as:

```
df1 <- draw_data(design_1)
df2 <- draw_data(design_2)
```
and then compare the dimensionality of the data and perhaps whether the moments are "similar"

## E Performance comparison 
Compare the diagnoses of the two designs

# Output

That's a lengthy list I know, and you might have other ideas. 

One might imagine wanting to indicate the type of comparison one cares about; or alternatively, have a report generation that does all of these. 

For all types though I think there is a permanent problem that some changes will just make automated comparison hard to evaluate. My sese is we just have to live with that and the compare function might just have to give up on some sorts of comparisons, but hopefully say why it is giving up (eg "unable to run design_2 estimates on data generated by design_1")

FWIW of the above C seems hardest to me and good answers to D and E might substitute for this. 

Sure others have thoughts

**Comment by graemeblair** [comment]
Pete's take a stab at something similar to A, a comparison of the code. What you're suggesting sounds like several different functions, so suggest we see how this first effort goes and then move on to other mechanisms for comparison.

**Comment by rdrr1990** [comment]
Thanks everyone for the comments and suggestions! I just pushed a fairly big commit to my branch which implements several of them. A 'github' style track changes is now the default for `compare_designs`. The full comparison can still be viewed per user input. Either way, a list is (invisibly) returned with the full comparison, the highlights, as well as similarity scores (designs compared by step). As the docs explain, similarity scores are based on Jaccard distance to the first design. `compare_designs(a, b, c, d)` will be compare the other three to `a`. Optionally (but by default) the code comparison will order things that way too. A few other little notes:

(1) The code tokenizes using regex, ignoring spaces and breaking on punctuation. The former is fairly harmless. The latter is more debatable in theory but I think will work well in practice. Breaking on punctuation lets you say `lm(y ~ x)` and `glm(y ~ x)` have a similarity score in the middle since `y ~ x` is in common, but, once tokenized, exact matching is used to distinguish `lm` from `glm`. Matching is also case sensitive which may allowing some distinction between `n` and `N`, which comes up a lot.
 
(2) I've started a little 'style guide' for best use in the `Rd`. The code actually handles a lot of this now but as we revise the function we still may want to encourage users to be consistent across designs.

```
#' Compare designs. For best results, use a consistent syntax style across designs 
#' (e.g., do not switch between '=' and '<-' for assignment or 
#' include optional parentheses on some designs but not others). 
```

(3) There are more problem cases to work through. In particular, Macartan's example where `N` is initialized to different values outside the declaration function calls. I have an idea on that one but am not positive if it will work yet...

(4) Here is some demo code

```R
library(DeclareDesign)

d1 <- declare_population(N = 100) +
      declare_assignment(m = 50) +
      declare_potential_outcomes(Y ~ rbinom(n = N, size = 1, prob = 0.5 + .1*Z)) +
      declare_estimand(ATE = 0.3) +
      declare_estimator(Y ~ Z)

d2 <- declare_population(N = 100) +
      declare_assignment(m = 50) +
      declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + .1*Z)) +
      declare_estimand(ATE = 0.3) +
      declare_estimator(glm(Y ~ Z, family = poisson))

d3 <- declare_population(N = 200) +
  declare_assignment(m = 100) +
  declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + .1*Z)) +
  declare_estimand(ATE = 0.3) +
  declare_estimator(glm(Y ~ Z, family = poisson))

compare_designs(d1, d2, d3)
```
and output
```
Highlights

[1] "declare_population(N = 200)"                                         
[2] "declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + 0.1 * Z))"
[3] "declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + 0.1 * Z))"
```

**Comment by nfultz** [comment]
Overall seems good. Ping me when you have a PR ready, there's some minor things that we can do to make this tighter (using dots_to_list_of_designs comes to mind, should make this behave the same as other helper functions that take ... designs, move pretty printing code into own print.design_comparison function, etc) 

For the actual logic itself, when there are 3 designs, I'm assumming it compares 1 vs 2, 1 vs 3? Would be nice if this were more explicit in the output, maybe add a column?.Or is it all vs all?

**Comment by rdrr1990** [comment]
Thanks.  And, yes, it compares 1 vs 2, 1 vs 3, etc, which seemed the most intuitive way to identify the scale for the user (i.e., allowing the user to treat the first model as a baseline seems better than pooling all tokens, which would imply comparing each model to some conglomerate which probably wouldn't be a valid design). 

Currently the similarity scores are returned:
```
> my_comparison <- compare_designs(d1, d2, d3, display = "none")
> my_comparison$similarity
   assignment population potential_outcomes reveal ra call
d1          1       1.00                1.0      1  1    1
d2          1       1.00                0.8      1  1    1
d3          1       0.75                0.8      1  1    1
``` 
And the sorting happens based on the `rowMeans()` of `similarity`. I can add a column to both that matrix and the others...

Thanks for the other suggestions--will get to work on those. As I'm new to the R side of this project, could I trouble you to let me know some representative functions that take `...` of designs as an argument?  (Tricky to search code for that, thx!)

**Comment by nfultz** [comment]
You can look at draw_estimates in https://github.com/DeclareDesign/DeclareDesign/blob/master/R/design_helper_functions.R

There's also todos for fixing diagnose and simulate to use idots_to_list_of_design also.

**Comment by macartan** [comment]
Thanks Pete. 

Noting that currently these designs are considered equivalent because of the embedded arguments issue:
```
design_1 <- simple_two_arm_designer(N = 10, ate = .2)
design_2 <- simple_two_arm_designer(N = 100, ate = -.2)
DeclareDesign:::compare_designs(design_1, design_2)
```

This is an argument for using the "fixed" option more in designers.

eg the differnece in the Ns for these two designers gets picked up

```
design_1 <- multi_arm_designer(N = 30, m_arms = 2, sd_i = 1, fixed = c("N")) 
design_2 <- multi_arm_designer(N = 50, m_arms = 2, sd_i = 2, fixed = c("N")) 
DeclareDesign:::compare_designs(design_1, design_2)

Highlights

[1] "declare_population(N = 50, u_1 = ~rnorm(50, 0, outcome_sds[1L]), u_2 = ~rnorm(50, 0, outcome_sds[2L]), u = rnorm(50) * sd_i)"
```                   
Can we make the highlight more informative about *where* the difference is?

**Comment by acoppock** [comment]
From a conversation today.  We think the goal is three kinds of functionality.

(1) a diff on the text output of a design
(2) compare outputs of draw_data, draw_estimates, draw_estimands. for estimates and estimands, maybe left_join?
(3) compare get_estimates(data = data_from_other_design)

**Comment by rdrr1990** [comment]
Thanks, @macartan will make another pass at this tricky issue

**Comment by rdrr1990** [comment]
thanks, @acoppock -- i will start expanding the functionality and see whether it looks like we should be housing this in one function or not (hopefully can)

**Comment by macartan** [comment]
ps and keep the structural comparison you are already doing: ie number of
steps of a particular type, in a given order....

**Comment by rdrr1990** [comment]
@macartan i don't think it will be necessary to require the user to do `fixed` input. Just pushed a version which tests steps for equality before tokenizing. The final similarity score is now a weighted average (`.05*equality_comparison + 0.95*similarity`). More nuance is needed to address all the issues but this is a simple catch all for things that slip through the cracks.
```
> d1 <- declare_population(N = 100) +
  declare_assignment(m = 50) +
  declare_potential_outcomes(Y ~ rbinom(n = N, size = 1, prob = 0.5 + .1*Z)) +
  declare_estimand(ATE = 0.3) +
  declare_estimator(Y ~ Z)

> d2 <- d1
> d2$population <-  declare_population(N = 101)

Highlights

[1] "declare_population(N = 101)"
```
Looks like the row label got lost on the highlights, will fix...

Also, `equality_comparisons` is now part of the `return`:
```
> decisions <- compare_designs(d1, d2, display="none")
> decisions$equality_comparisons
   assignment population potential_outcomes reveal   ra call
d1       TRUE       TRUE               TRUE   TRUE TRUE TRUE
d2       TRUE      FALSE               TRUE   TRUE TRUE TRUE
```

**Comment by macartan** [comment]
OK. To be clear by "fixed" I mean that the code has something like N = 10, rather than N = N. 

Currently without fixing,  we have 

```
> library(DesignLibrary)
> design_1 <- simple_two_arm_designer(N = 10, ate = .2)
> design_2 <- simple_two_arm_designer(N = 100, ate = -.2)
> DeclareDesign:::compare_designs(design_1, design_2)

Highlights

character(0)
```

Cheers

**Comment by rdrr1990** [comment]
Thanks for those notes, @macartan! I took another pass, focused on the code found in the attributes. I test whether the attributes of each design are identical to those of the first design and updated the final similarity score to reflect that (it's now `similarity <- 0.05*identical_attr_to_design1 + .05*equality_comparisons + 0.9*similarity`). Also, if those tests flag any differences, they are returned and/or displayed.
```
> design_1 <- simple_two_arm_designer(N = 10, ate = .2)
> design_2 <- simple_two_arm_designer(N = 100, ate = -.2)
> compare_designs(design_1, design_2)


Highlights

           design_1     design_2                  
           "N  <-  10"  "treatment_mean  <-  0.2" 
code_diffs "N  <-  100" "treatment_mean  <-  -0.2"
```

**Comment by macartan** [comment]
Thanks Pete -- that's useful. 

* My sense is that we should keep this as an operation and list it as a point of difference. ("Differences found in code attribute")

* In general though this code attribute is often not present; for example design_1 <- design_1 + step  will remove the code. GIven this I imagine two other approaches

* One is going into the deep design --- comparing things in the environments of similarly names steps. Do any objects in environments differ. I know this is hard and maybe impossible but worth exploring I think.

* The other is the functional approach. Comparing the dimensions of the dataset as it moves through the pipe.
 

BTW you may have thought of this or have views but I wonder if any of the test_that functionality would be useful for comparing designs. eg for comparing the structure of steps

**Comment by rdrr1990** [comment]
Hi all,

Just re-opening this thread. Apologies for the radio silence but, as some of you may know, it was for the happy reason that my wife and I welcomed our first child into the world. (Our son Wylie was born in the wee hours of Halloween. Also very happy to say that he and his mother are doing quite well.)

I've found a few hours here and there to work on `compare_designs`. Though I have a few more things to check before submitting a PR, this is a good point to have a look at the somewhat substantial update...

(1) Added additional tests of equality between designs.

(2) Added a print S3 method so that printing can be done when `compare_designs` is initially called or later on from the stored object. Also improved the readability of the output a fair bit...

(3) Enabled both `compare_designs` and its print method to create an `Rmd` template. Users might use this at early stages, especially if someone on their research team doesn't use R and would prefer docx or something. Users might also like this at the end stages when they are writing up appendices or online supplemental materials and looking for a concise reason to explain why they chose one design over the other.

To see the new functionality... 

```
library(DeclareDesign)

d1 <- declare_population(N = 100) +
  declare_assignment(m = 50) +
  declare_potential_outcomes(Y ~ rbinom(n = N, size = 1, prob = 0.5 + .1*Z)) +
  declare_estimand(ATE = 0.3) +
  declare_estimator(Y ~ Z)

d2 <- declare_population(N = 100) +
  declare_assignment(m = 50) +
  declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + .1*Z)) +
  declare_estimand(ATE = 0.3) +
  declare_estimator(glm(Y ~ Z, family = poisson))

d3 <- declare_population(N = 200) +
  declare_assignment(m = 100) +
  declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + .1*Z)) +
  declare_estimand(ATE = 0.3) +
  declare_estimator(glm(Y ~ Z, family = poisson))

# compare_designs(d1, d2, d3) # displays to console as early version
# my_comparison <- compare_designs(d1, d2, d3) # stores object and displays

compare_designs(d1, d2, d3, Rmd_file_prefix = "short_report")
compare_designs(d1, d2, d3, display = "all", Rmd_file_prefix = "full_report")
``` 
Executing the last two lines ...
```
> compare_designs(d1, d2, d3, Rmd_file_prefix = "short_report")
DeclareDesign RMarkdown comparison template created. The file is called short_report.Rmd.

> compare_designs(d1, d2, d3, display = "all", Rmd_file_prefix = "full_report")
DeclareDesign RMarkdown comparison template created. The file is called full_report.Rmd.
```
   
Cheers,
Pete

**Comment by macartan** [comment]
Hi Pete -- I spent a bunch of time with this today. I did in a separate branch in case you don;t like some of the directions. Branch is compare_designs

* I worked a bit with some of the elements, eg the character count and the code comparison
* Added some, eg draw_data dimensionality comparison
* Suggest an approach to add attributes to each summary element for a very quick comparison output; currently looks like this:
```
> my_comparison <- compare_designs(d1, d2, d3) # stores object and displays
[1] "Comparison: Number of steps, for each design. Differences? FALSE"
[1] "Comparison: Dimensionality of drawn data. Differences? TRUE"
```
but should be connected with printing method
* That's the main thing structurally -- if we add comparisons like this we end up with a nice list of annotated dimensions of comparison; one might even select some of these for a report
* Commenting in lots of places
* Some work on the Rmd structure, including simplification. 
* I introduced some use of kable but think this can be done better; currently the kable(text) is exported to Rmd rather than "kable(text)" so does not compile quite so nicely; also we will need some wrapping I think
* Think worth adding comparisons of diagnoses
* We should think of including a data argument for comparison since this will be relevant for post study PAP reconciliation
* If you are happy I suggest either merge into yours or lets keep going on this branch
* Thanks for the good work here so far 
Sample output:

---
title: DeclareDesign Comparisons
output:
      html_document:
           toc: true
           number_sections: true
---

# Overview of comparisons of  2 designs 
 

This report compares the following designs: planned_design, implemented_design.


 Number of steps per design: 
 
```r


                    planned_design   implemented_design
-----------------  ---------------  -------------------
Steps per Design                 6                    7
```
When relevant, comparisons are made relative to planned_design.


## Steps compared 
 

 Design steps compared:  assignment, population, potential_outcomes, reveal, call 
 

## Steps with differences in code 
 

 Summary of steps that exhibit some code differences across designs: 
 
```r
[1] "assignment" "estimator"  "sampling"  
```

 Specifically: 
 
```r


             planned_design               implemented_design                                      
-----------  ---------------------------  --------------------------------------------------------
assignment   declare_assignment(m = 50)   declare_assignment(m = 40)                              
estimator    declare_estimator(Y ~ Z)     declare_estimator(Y ~ Z, family = poisson, model = glm) 
sampling     NA                           declare_sampling(n = 80)                                
```

# Detail 
 

## Differences in Data structure 
 
```r


                      rows   cols
-------------------  -----  -----
planned_design         100      6
implemented_design      80      7
```

## Tests for Equality Across Step Types 
 
```r
                   assignment population potential_outcomes reveal call
planned_design           TRUE       TRUE               TRUE   TRUE TRUE
implemented_design      FALSE       TRUE               TRUE   TRUE TRUE
```

## Code Overview 
 

### assignment 
```
 

planned_design: declare_assignment(m = 40) 

implemented_design: declare_assignment(m = 50) 
 
```

### population 
```
 

planned_design: declare_population(N = 100) 

implemented_design: declare_population(N = 100) 
 
```

### potential_outcomes 
```
 

planned_design: declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + 0.1 * Z)) 

implemented_design: declare_potential_outcomes(Y ~ rpois(n = N, lambda = 0.5 + 0.1 * Z)) 
 
```

### reveal 
```
 

planned_design: declare_reveal(Y, Z) 

implemented_design: declare_reveal(Y, Z) 
 
```

### call 
```
 

planned_design: construct_design(steps = steps) 

implemented_design: construct_design(steps = steps) 
 
```

**Comment by rdrr1990** [comment]
Thanks--look forward to comparing with that branch! Just before the holiday, I got most of the way through integrating additional tests based on the existing summary S3 for design objects, which captures even more corner cases.

**Comment by macartan** [comment]
Hi Pete -- if you could synch that up it would be great; I hadn't realized
that was done; happy to look through. Even better if you could combine with
what I have in the compare_designs branch, would make it easier to give
support for pushing this forward

Cheers

M

**Comment by rdrr1990** [comment]
Apologies for delay, working on this now!

**Comment by graemeblair** [comment]
can we use this new package to spruce things up? https://github.com/brodieG/diffobj

**Comment by rdrr1990** [comment]
that looks beautiful! Will look into it. Two questions I'll have: will it display nicely on larger objects? Will it work well on custom classes?

**Comment by nfultz** [comment]
If it doesn't work on functions, it probably won't work for design steps
(which are functions)

**Comment by rdrr1990** [comment]
yeah, I'm somewhat skeptical that it will work on entire `DeclareDesign` or `DesignComparison` objects (the latter includes several input sources, including entire summaries) but hopeful that `diffobj` can provide some value added.
