### ISSUE TITLE
fan_out syntax

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#266]
In one of the tests, we have:

```
  sleep_large <- resample_data(sleep, N = 200)
  design <- declare_population(sleep_large) +
    declare_estimand(2, label = "a") +
    declare_estimand(b = rnorm(1))
  
  fan <- data.frame(end = 1:3, n = c(5, 5, 5))

  fo <- diagnose_design(design, sims = fan)
```

This seems like it's testing internal functionality, but it's causing trouble in `simulate_design`.  @nfultz , are we correct in thinking that user will only ever pass a vector to `sims` and not a data.frame?

**Comment by nfultz** [comment]
I guess that part is not well tested. 

this is probably false positive bc data.frames are also lists, but not sure. see also 

https://github.com/DeclareDesign/DeclareDesign/blob/777300df96f7e6ea35bf5e2bd37c6dc1e00e35d9/R/simulate_design.R#L72

**Comment by acoppock** [comment]
yes, that's part of the problem -- but I guess my intuition is that users should always either pass a scalar or a numeric vector to `sims`.  It would make sense to me to check that and not allow passing something like `data.frame(end = 1:3, n = c(5, 5, 5))`. but I don't want to break it if there was some good purpose behind it?

**Comment by nfultz** [comment]
It uses that representation internally so that if you have 5 steps ABCDE
and fold out at C, AB and CDE are executed by block together (eg same R
thread)- if you are using futures for parallelism, this is very important,
otherwise each step would need a full copy of the execution state and
fanning out can be very memory intensive already.

If it's exposed externally, doesn't matter to me, but internally we need
the sparse representation.

**Comment by acoppock** [comment]
Ok, we will not expose this to the user.  Thanks.
