### ISSUE TITLE
think about allowing multiple estimands per declare_estimand call

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#32]
i.e. 

```
my_estimand <- declare_estimand(SATE = 3, PATE = 4)
```

as we allow in declare_potential_outcomes would make things considerably simpler. We'd tie things together via the labels rather than the object name, i.e. in this case,

`my_estimator <- declare_estimator(Y ~ Z, estimand = SATE)` rather than the current `my_estimator <- declare_estimator(Y ~ Z, estimand = my_estimand)`

**Comment by graemeblair** [comment]
More broadly, need to think about how to allow for vector-valued estimators and estimands, i.e. if you have a model and you are interested in properties of two of the coefficients so you return both estimates from the model and want to relate them to two estimands.

**Comment by nfultz** [comment]
`estimand(df)` should return a `data.frame` - we just never return more than one row right now AFAIK. In `diagnose_single_design` we do:

```
 merge(
          estimands_df,
          estimates_df,
          by = c("sim_ID", "estimand_label"),
          all = TRUE,
          sort = FALSE
        )
```

which matches up with this column built in `declare_estimator` : 

```
  estimand_label <- if(is.null(estimand)) NULL else attributes(estimand)$label
```

That label *should* be possible to be a vector... the attribute is set in `declare_estimand` by some `substitute` logic I'm trying to figure out. But I think we can edit the line above to check if `estimand` is a result of `declare_estimator`, if yes use the attributes, otherwise check if it's a symbol/character and use that instead.

**Comment by graemeblair** [comment]
this works now / we have separate issues for multiple estimate/estimand combos
