### ISSUE TITLE
get_estimates_data() using get_estimates()

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#337]
Would it be possible to have sthg like 

```
get_estimates <- function(design, data = NULL) {
  if(!is.null(data) return(get_estimates_data(design, data)
  ...
```

ie so users do not have to call a separate function when they have data but get the same results when they provide data to get_estimates

**Comment by nfultz** [comment]
Flag arguments are generally an anti-pattern - see
https://martinfowler.com/bliki/FlagArgument.html

Since there are important differences between the two (one runs an entire
design and returns simulated estimates, one only runs a small number of
steps and returns actual estimates) they ought to be kept seperate.


Any user progam that used to call get_estimates_data would have to be
updated to correctly check it's input to error instead of silently
returning simulated data., It would be a pretty nasty issue to  find out
your final results were actually simulated because you accidently didn't
update your program correctly and it didn't issue any warnings or errors.
If you did combine the two functions, you need to warn the user and make
this situation clear.

I think get_estimates_data is not a good name, would suggest
"get_actual_estimates" or anything else that makes the intent much more
obvious.

**Comment by macartan** [comment]
I see the point. 
It may be too late for this but natural names would be:
simulate_estimates(design)
get_estimates(design, data)

**Comment by nfultz** [comment]
Closing this out. We may want to follow up at some point to tag simulation output accordingly so that it can be distinguished from real output w/o reading code.

**Comment by graemeblair** [comment]
how about

draw_data (as is)
draw_estimates (simulates estimates, current get_estimates)
draw_estimands (simulates estimands, current get_estimands)
get_estimates (current get_estimates_data)

**Comment by macartan** [comment]
I like that
But is it not too late if people are using get_estimates already?
If maybe if data not provided issue message --- for simulated estimates use
draw estimates

**Comment by nfultz** [comment]
I think it would be OK if there was an appropriately chatty error message -
then people could be directed to use draw_estimates instead.

**Comment by graemeblair** [comment]
I think there's a tradeoff given users, but that you've convinced me this would be much more communicative. I agree with you both if error message is clear we can make the change now.
