### ISSUE TITLE
when an estimator sometimes returns a diff number of columns, problems

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#380]
```

library(DeclareDesign)
population <- declare_population(N = 100, Y = runif(N), Z = sample(0:1, N, replace = TRUE))

estimator1 <- declare_estimator(Y ~ Z)

estimator2 <- declare_estimator(
  handler = function(data) {
    if(sample(0:1, 1)){
      estimator1(data)
    } else {
      return(
        data.frame(
          estimator_label = "No Model",
          term = "X",
          outcome = "Y"
        ))
    }
  }
)

design <- population + estimator2

# works
run_design(design)

# does not work
simulate_design(design, sims = 5)


# this version works, with the same two estimators but split out and included separately

library(DeclareDesign)
population <- declare_population(N = 100, Y = runif(N), Z = sample(0:1, N, replace = TRUE))

estimator1 <- declare_estimator(Y ~ Z, label = "est1")

estimator2 <- declare_estimator(
  handler = function(data) {
        return(data.frame(
          estimator_label = "No Model",
          term = "X",
          outcome = "Y"
        ))
    }
)


design <- population + estimator1 + estimator2

# works
draw_estimates(design)

# works
simulate_design(design, sims = 5)
```

**Comment by nfultz** [comment]
Do you have an use case for when an estimator would sometimes not have
estimate columns? I feel like we should tell not people to do this or
encourage it in any way. It should be an error.

**Comment by graemeblair** [comment]
The use case is a procedure where you try one estimator and if that doesn't work you try another; using off the shelf stuff that will sometimes mean one has a p-value and one does not for examle

**Comment by nfultz** [comment]
That's in the context of a custom handler - if they are already writing
custom code for fallback estimation, they can easily add or drop columns as
needed. "Don't change columns run-to-run" is a very modest requirement for
the API, probably not documented since it never came up.


Also I think having the fallback estimate in the same step and not
distinguishable from the preferred one will make the resulting diagnostics
difficult to interpret in the best case and  GIGO in the worst. What does a
bias of -2 mean when 80% of the runs are from one model and the others are
from something else? What you really want to know is the bias if the first
succeeds, and the bias  of the fallback given the first fails.

If you implement the other ticket for catching errors, then I think it
makes more sense to have people run the two models in two seperate steps,
and then use a many-to-one estimate-estimand link - this would both capture
more data and tag where each estimate came from correctly, without forcing
people to do that book keeping in a custom handler.
