### ISSUE TITLE
issue running assignment steps

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#392]
it looks like the two assignment steps get run ignoring the sampling step in between but this matters because it changes the assignment; of course running the sampling step is also a problem because you lose information on the first assignment

maybe the function really has to do just one assignment step at a time?

```
design <- 
    declare_population(N = 6, strata = c(1,1,1,1,2,2)) +
    declare_assignment(prob = .5)+
    declare_sampling(strata = strata, strata_prob = c(0,1)) +
    declare_assignment(prob = .5, assignment_variable = "W") 

draw_data(design)

df <- design[[1]]()
df

draw_assignment(design, df)
```

**Comment by acoppock** [comment]
This one is tough!

As written, the function can give unexpected results:

```
library(DeclareDesign)

design <- 
  declare_population(N = 6, strata = c(1,1,1,1,2,2)) +
  declare_assignment(prob = .5)+
  declare_sampling(strata = strata, strata_prob = c(0,1)) +
  declare_assignment(prob = .5, assignment_variable = "W") 

# this is wrong
data_through_step_one <- draw_data(design, end = 1)
draw_assignment(design, data_through_step_one)

# this is wrong too
data_through_step_three <- draw_data(design, end = 3)
draw_assignment(design, data_through_step_three)

# we really want
design[[2]](data_through_step_one)
# and
design[[4]](data_through_step_three)
```

It's hard to know what to do here! 

1. We could do nothing except explain to users that these draw_* functions just run all the functions of a particular kind on the provided data frame.
2. We could restrict to just one such function at a time, but then we'd need a way for users to tell us which one.  This is sort of duplicating functionality, because the declarations are literally these functions. If you're not using the pipeline format, you could just do:

```
pop <- declare_population(N = 6, strata = c(1, 1, 1, 1, 2, 2))
assign_1 <- declare_assignment(prob = .5)
sampling <- declare_sampling(strata = strata, strata_prob = c(0, 1))
assign_2 <- declare_assignment(prob = .5, assignment_variable = "W")

design <- pop + assign_1 + sampling + assign_2

data_through_step_one <- draw_data(design, end = 1)
assign_1(data_through_step_one)

data_through_step_three <- draw_data(design, end = 3)
assign_2(data_through_step_three)
```

If you're not using pipeline, then you have to do ```design[[4]](data)```

3. A third option is to remove the draw_sampling and draw_assignment functions altogether since they can sometimes generate unexpected output?

Is there another option I'm not seeing?

**Comment by nfultz** [comment]
I thought you could specify start and end steps on draw_assignment?
