### ISSUE TITLE
coerce estimator_label to factor?

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#395]
Factors are creeping into diagnosis and causing problems including in `reshape_diagnosis` via `estimator_label` in custom estimators (and custom estimands), e.g.:

```
population <- declare_population(N = 100)

estimator <- declare_estimator(handler = function(data) {
  data.frame(estimator_label = "my_estimator", est = 5)
})

simulate_design(population + estimator, sims = 5) %>% as_tibble %>% head

# A tibble: 5 x 4
  design_label sim_ID estimator_label   est
  <chr>         <int> <fct>           <dbl>
1 design_1          1 my_estimator        5
2 design_1          2 my_estimator        5
3 design_1          3 my_estimator        5
4 design_1          4 my_estimator        5
5 design_1          5 my_estimator        5
```

Suggest we coerce with `as.character` at the `get_estimates/draw_estimates` stage. Objections?

Of course this can be fixed by the user via `stringsAsFactors = FALSE` but seems people forget this often.

**Comment by nfultz** [comment]
That seems fine, but we should also `warning()` after the estimator step so that users know to fix it. Also worth noting that this affects bare custom handlers - the `tidy_estimator` wrapper does the labeling correctly and would be the recommend fix for whoever encountered this.  This also does not affect when people use the regular handler with a different model, so it's fairly narrow.

**Comment by graemeblair** [comment]
+1 to all of this thanks

**Comment by graemeblair** [comment]
where do you suggest the warning goes -- since this is a custom handler and doesn't go through tidy_estimator - should be in `run_design`?
