### ISSUE TITLE
filter as handler not working

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#444]
Many dplyr functions work as handlers, but can't get filter to work as I would expect. The function args look the same between mutate and filter, so not sure what could be going on.

```
> library(DeclareDesign)
> library(dplyr)
> des1 <- declare_population(N = 2, X = c(TRUE, FALSE)) + 
>   declare_step(handler = mutate, X  = 1)

> draw_data(des1)
   ID X
1  1 1
2  2 1

> des2 <- declare_population(N = 2, X = c(TRUE, FALSE)) + 
>  declare_step(handler = filter, X == TRUE)

> draw_data(des2)
Error: Error in step 2 ():
	Error in ~X == TRUE: object 'X' not found 
```

**Comment by nfultz** [comment]
Note that in the mutate case, the X is passed as a named arg, vs in filter, it's NSE - I do see the same error using subset:

```
>  des2 <- declare_population(N = 2, X = c(TRUE, FALSE)) + 
+     declare_step(handler = subset, X)
>  draw_data(des2)
Error: Error in step 2 ():
	Error in ~X: object 'X' not found
``` 

Probably an NSE overscoping issue ?

EDIT:

When you force mutate to use NSE (eg read `X` instead of `1`), its fine?

```
des1 <- declare_population(N = 2, X = c(TRUE, FALSE), Y = 1:2) + 
     declare_step(handler = mutate, Y=X)
draw_data(des1)
```

Weird.


EDIT2:

In the debugger, you can see the step is constructed incorrectly - 

```
> debugonce(des2[[2]])
>  draw_data(des2)
debugging in: step(current_df)
debug: eval_tidy(quo, data = list(data = data))
Browse[2]> quo
<quosure>
expr: ^(FUN)(.data = ^X == TRUE)
env:  0x5571c282a8f8
```


EDIT3:

In debugger of, it appears that 

```
Browse[2]> dots
$.data
<quosure>
expr: ^X == TRUE
env:  0x5571c2254068
```

dots now has a named element `.data` which matches the test here, preventing the data argument from being added to the quosure:

https://github.com/DeclareDesign/DeclareDesign/blob/fccf8ba9e89ac44ddf995b81dcb08be2dc18de28/R/aaa.R#L78  


EDIT4:

See also 

https://github.com/DeclareDesign/DeclareDesign/blob/fccf8ba9e89ac44ddf995b81dcb08be2dc18de28/R/declare_step.R#L3

It looks like the PR for hadley names was written rather narrowly - https://github.com/DeclareDesign/DeclareDesign/issues/398


EDIT5:

Based on above, I think the believe the correct way to fix this to be modifying `rename_dots` to check the handler function for `.data` - right now it always adds `data` no-dot, which messes up the positional argument matching there. `mutate()` was working before because you always and only provide named arguments, so no positional matching occurred.  

EDIT6:

Until rename_dots is fixed, this is a workaround:

```
des2 <- declare_population(N = 2, X = c(TRUE, FALSE)) + 
  declare_step(handler = filter, .data=data, X == TRUE)

 draw_data(des2)
```

**Comment by nfultz** [comment]
short summary of handler required

* Original:
  * handlers required a `data` argument 
* #398 added support for mutate
  * Also allowed handlers that used `.data` as first argument, all other arguments must be named
  * Not really documented.

## Proposed new requirements

* If the step is a population step in the first position, do nothing.
* if the `data` symbol is passed as an argument (RHS of named parameter) to a step declaration, that named parameter will be used (via overscoping).
* If a handler function has an paramater named `data` or `.data` in any position, it will be the parameter used by DeclareDesign to pass through a design.
  * If, somehow, a handler has both, `data` will be preferred.
* Lacking `data`/`.data`, the first paramater will be used positionally and a warning printed to console.
  * This would make `subset` etc work.
  * If the handler function has a single arg `value` and inherits fseq, eg dot-pipes, use that and do not warn.
