### ISSUE TITLE
possible changes to diagnose() 

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#59]
_From @graemeblair on February 11, 2016 19:40_

Output of new diagnose_design is a data.frame with these columns:

population_draw_index sample_draw_index assignment_draw_index design est se ci_lower ci_upper df estimand

Then compare_designs does this several times and joins them with a variable for what is it varying over (i.e. it adds a compare_N column with which N this row is for).

To be discussed/implemented soon! Thanks to Alex for this amazing idea!

_Copied from original issue: DeclareDesign/DeclareDesign-dev#227_

**Comment by jaspercooper** [comment]
Compare designs now outputs a single "diagnosands" and a single "simulations" data.frame. Quick  design generates labels by default if you are varying. If there are no variable labels specified, there is always at a minimum a "diagnosis" index enabling users to distinguish between each diagnosed design. 

Closing because all of these are now implemented
